### PR TITLE
benchmarks: try out new setup

### PR DESCRIPTION
**Pull request by pared**
This is the first approach to modifying benchmarks setup. 
@iterative/engineering I would love your opinion on that example.
What I wanted to achieve here is something pytest-like. Due to proxy-ing execution to `asv` it's not that easy.

### CODE REVIEW

**Comment by Suor** [comment]
Good idea approach-wise, looks really heavy though. You save in code in no place and add a level of indirection. You also use both inheritance and fixtures, which intermixes two worlds.

**Comment by pared** [comment]
@Suor thanks, the problem I have is that how `asv` executes the benchmarks:
if the benchmark has `setup`, it gets executed, then the benchmark code gets executed, and then teardown. That is the main reason for intermixing. I'll think about how can I modify it.

**Comment by efiop** [comment]
@pared Maybe we should just keep it simple for now, and do as numpy/etc. There is a ticket for supporting pytest in asv, maybe sooner or later it will be implemented and we could switch to it.

**Comment by pared** [comment]
@efiop 
Considering that we will probably not have as much benchmarks as we do have tests, that makes sense, at least for now.

**Comment by pared** [comment]
closing for now

**Pull request closed without merging**
