### PR TITLE
readme: instructions on testing local changes

### PR DESCRIPTION
**Pull request by pared**
Instructions on how to run benchmarks on local copy of DVC.

### CODE REVIEW

**Comment by karajan1001** [comment]
@pared  Thank you.
 I followed the instruction But there is one question.
Screenshot from 2020-06-11 22-47-28
The benchmark runs and I can see it the running resulting in the log.
But there is no result in `asv publish && asv preview`
Screenshot from 2020-06-11 22-47-34

**Comment by pared** [comment]
@karajan1001 
hmm, so you have run `dvc repro benchmarks.dvc` right? And you wanted to verify whether your change has an influence on one of the tests?
Btw, what is the contents of your `tags.txt` file? 
`1.0.0a1`?

**Comment by karajan1001** [comment]
> @karajan1001
> hmm, so you have run `dvc repro benchmarks.dvc` right? And you wanted to verify whether your change has an influence on one of the tests?
> Btw, what is the contents of your `tags.txt` file?
> `1.0.0a1`?

I didn't change it. I simply locked the `convert_tags.dvc` and changed `hashes.txt` manually.

**Comment by pared** [comment]
@karajan1001, ok so you edited `hashes.txt`, so that there would be only master hash and your branch hash, right?

> And I tried adding a new tag 1.0.0a1test to my local repo, but I got this
Hmm, not sure what happened here, is this tag on a master or your branch? I think asv by default analyses only master.

**Comment by efiop** [comment]
> Hmm, not sure what happened here, is this tag on a master or your branch? I think asv by default analyses only master.

You mean the upstream? Asv has our upstream repo hardcoded and the new tag that @karajan1001 created is only in his own repo, so that's probably why it is not able to find that tag.

**Comment by karajan1001** [comment]
> Hmm, not sure what happened here, is this tag on a master or your branch? I think asv by default analyses only master.

Maybe the case.



> > Hmm, not sure what happened here, is this tag on a master or your branch? I think asv by default analyses only master.
> 
> You mean the upstream? Asv has our upstream repo hardcoded and the new tag that @karajan1001 created is only in his own repo, so that's probably why it is not able to find that tag.

It can find the tag. I edited `asv.conf.json` and made it point to my own repo.
```
-    "repo": "https://github.com/iterative/dvc",
+    "repo": "https://github.com/karajan1001/dvc",
```

And this is its result 
Screenshot from 2020-06-13 20-40-30

But after I use `asv publish && asv preview`
Screenshot from 2020-06-13 20-40-45

It shows 
```
[ 33.33%] ·· Couldn't find 43dcc97512f7cc49dd24139334f89db909105df6 in dict_keys([None]) branches
[ 33.33%] ·· Couldn't find 6ab06bbf9e3dfea552e14b626d5618bfdfe2384d in dict_keys([None]) branches
[ 33.33%] ·· Couldn't find 93d7b9173b8630db7cc21df606040677dc3753d7 in dict_keys([None]) branches
[ 33.33%] ·· Couldn't find a338fad036bd9ac8bdd79ecec964f8c5558609c4 in dict_keys([None]) branches
[ 33.33%] ·· Couldn't find a86cedbf39919923d54b0754b64c412433a8f5b1 in dict_keys([None]) branches
[ 33.33%] ·· Couldn't find a90d7009f52fa03b45ad5c1d22943cebee387b01 in dict_keys([None]) branches
[ 33.33%] ·· Couldn't find c5bac1c8cfdb2c0f54d52ac61ff754e6f583822a in dict_keys([None]) branches
[ 33.33%] ·· Couldn't find fc42ca721c25bdd24875c999e37fb4f589ecd63c in dict_keys([None]) branches
```

The `tags_to_sha.py` can find the tag but the ASV can't

**Comment by pared** [comment]
@karajan1001 interesting. Can I ask you to change the URL to your local copy of DVC and try again?

**Comment by karajan1001** [comment]
> @karajan1001 interesting. Can I ask you to change the URL to your local copy of DVC and try again?

I had tried this. But this time, it could not transfer tags to hashes. 
```
-    "repo": "https://github.com/iterative/dvc",
+    "repo": "/home/gyx/code/dvc",
```

**Comment by pared** [comment]
@karajan1001 
Seems to me like `asv` has problems with cloning the repo. So before `dvc repro run_benchmarks.dvc` please run `git clone /home/gyx/code/dvc dvc`. I tried locally, and was able to translate local-only tag

**Pull request merged**
