### PR TITLE
Add a benchmark for imports

### LINKED ISSUE #213: benchmark for imports
See https://github.com/iterative/dvc/issues/4485, it'd be better to have this tracked, as our upcoming changes might affect these, specifically "subrepo support" and "hashing dir checksums in-memory" (cc @efiop).

### PR DESCRIPTION
**Pull request by skshetry**
Fixes #213

### CODE REVIEW

**Comment by pared** [comment]
Looks great!
About dataset:
If dataset registry changes, we might not notice that fact. Maybe we should consider importing from this repo, but from github? like URL = `https://github.com/iterative/dvc-bench` and path = "data/cats_dogs"? @skshetry what do you think? Or we could set revision for `dataset-registry` so that we minimize the possibility of importing different data, if it was ever going to change.

**Comment by skshetry** [comment]
@pared, I tried doing that (even using local `dvc-bench` repo instead of Github), but the registry's public remote is not set as a default in this repo. Not sure how to achieve that.

**Comment by pared** [comment]
@skshetry let me fix that

**Comment by pared** [comment]
I am trying to run this benchmark locally with `asv run --bench ImportBench -e`, but it seems like it fails with `no AWS credentials`. Need to investigate why it happens, public s3 should not require that.

**Comment by skshetry** [comment]
@pared, probably because this needs a rebase.

**Comment by skshetry** [comment]
@pared, rebased. Should be fixed.

**Comment by pared** [comment]
@skshetry Yep, I did it on previous version of branch.

**Comment by efiop** [comment]
@skshetry Thank you so much! :pray:

**Pull request merged**
